# Generated by Django 2.1.15 on 2020-05-31 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egiftadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
